model:
  base_learning_rate: 1.0e-6
  target: refnet.models.trainer.sdxl.GramTrainer
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: reference
    control_key: control
    score_key: aesthetic_score
    image_size: 128
    channels: 4
    scale_factor: 0.13025
    use_ema: false
    ucg_rate: 0.2
#    ucg_range: 0.55
    inpaint_p: 0.1
    offset_noise_level: 0.05
    token_type: full
    pooled_wd_emb: false
    parameterization: v
    control_drop: [ 0.1, 0.1, 0.1, 0.1 ]
    thresh_min: 0.05
    smask_required: true

    gram_start_epoch: 2.
    gram_clip_proj_grad: false

    gram_config:
      hooker:
        gram_ids: [23, 63]
        gram_type: ff
        apply_dist_norm: false
        apply_norm: true
      loss:
        weight: 1.0
        mask_weight: false
        loss_fn: mse_loss

    unet_config:
      target: refnet.modules.unet.DualCondUNetXL
      params:
        use_checkpoint: True
        in_channels: 4
        out_channels: 4
        model_channels: 320
        adm_in_channels: 512
        num_classes: sequential
        attention_resolutions: [4, 2]
        num_res_blocks: 2
        channel_mult: [1, 2, 4]
        num_head_channels: 64
        use_spatial_transformer: true
        use_linear_in_transformer: true
        transformer_depth: [1, 2, 10]
        context_dim: 2048
#        additional_transformer_config:
#          rotary_positional_embedding: true
#          qk_norm: true

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 512
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [1, 2, 4, 4]
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0

    cond_stage_config:
      target: refnet.modules.embedder.HFCLIPVisionModel
      params:
        arch: ViT-bigG-14

    img_embedder_config:
      target: refnet.modules.embedder.WDv14SwinTransformerV2

    control_encoder_config:
#      target: refnet.modules.encoder.MultiEncoder
      target: refnet.modules.encoder.MultiScaleAttentionEncoder
      params:
        in_ch: 3
        model_channels: 320
        ch_mults: [1, 2, 4]

    proj_config:
      target: refnet.modules.proj.ClusterConcat
#      target: refnet.modules.proj.RecoveryClusterConcat
      params:
        input_dim: 1280
        c_dim: 1024
        output_dim: 2048
        token_length: 196
        dim_head: 128

    scalar_embedder_config:
      target: refnet.modules.embedder.TimestepEmbedding
      params:
        embed_dim: 256


dataloader:
  class: QuartLoader
  use_aspect_ratio_sampler: true
  dataset_params:
    json_files:
      - landscape
      - portrait
      - square
      - landscape_with_reference
      - portrait_with_reference
      - square_with_reference
    condition_key: color
    minimum_image_size: 768
    score_threshold: 5.5
  transforms:
    transform_list:
      flip: false
      rotate: false
      resize: true
      jitter: false
      rotate_range: 45
    load_size: 1280
    crop_size:
      - [ 1024, 1024 ]
      - [ 1024, 1024 ]
      - [ 1024, 1024 ]
      - [ 1024, 1024 ]
      - [ 992, 1056 ]
      - [ 1056, 992 ]
      - [ 960, 1088 ]
      - [ 1088, 960 ]
      - [ 928, 1120 ]
      - [ 1120, 928 ]
      - [ 896, 1152 ]
      - [ 1152, 896 ]
      - [ 864, 1184 ]
      - [ 1184, 864 ]
      - [ 832, 1216 ]
      - [ 1216, 832 ]
      - [ 800, 1248 ]
      - [ 1248, 800 ]
      - [ 768, 1280 ]
      - [ 1280, 768 ]
      - [ 736, 1312 ]
      - [ 1312, 736 ]
    keep_ratio: false
    inverse_grayscale: true
    erase_p: 0.33
    mask_expansion_p: 0.33
  shuffle: true